#!/usr/bin/env bash
# contract-mirror.test.sh: suite for contract-mirror.sh.
#
# WHY THIS EXISTS
# The incident this locks down: a generated OpenAPI types file gained schemas
# (SearchResult, Citation, CrossMeetingChat*) while a handwritten client kept
# mirror interfaces of the same names under a comment claiming the generated
# file "predates that addition and isn't regenerated". The forward
# regenerate-and-diff check can never see that, because the mirror is not at a
# generated path. Every fixture here is synthetic; the suite replays the shape,
# not the source.
#
set -uo pipefail

SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/contract-mirror.sh"
pass=0; fail=0

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t

ok()   { printf '  ok   %s\n' "$1"; pass=$((pass+1)); }
bad()  { printf '  FAIL %s\n' "$1"; fail=$((fail+1)); }
check(){ # check <desc> <expected-substring> <actual>
  if grep -qF "$2" <<<"$3"; then ok "$1"; else
    bad "$1"; printf '       wanted: %s\n       got:\n%s\n' "$2" "$(sed 's/^/         /' <<<"$3")"
  fi
}
absent(){ # absent <desc> <substring-that-must-not-appear> <actual>
  if grep -qF "$2" <<<"$3"; then
    bad "$1"; printf '       must NOT contain: %s\n' "$2"
  else ok "$1"; fi
}

newrepo(){ d=$(mktemp -d); ( cd "$d" && git init -q . ); echo "$d"; }
run(){ ( cd "$1" && bash "$SCRIPT" 2>&1 ); }

# gen_ts <path>: a synthetic openapi-typescript output file. The schema names
# exist ONLY as object keys, exactly like the real generator's output, so the
# suite locks the schemas-block extractor and not just the export grep.
gen_ts() {
  mkdir -p "$(dirname "$1")"
  cat > "$1" <<'EOF'
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface components {
    schemas: {
        SearchResult: {
            meetingId: string;
            score: number;
        };
        SearchResults: {
            results: components["schemas"]["SearchResult"][];
        };
        Citation: {
            meetingId: string;
        };
        CrossMeetingChatRequest: {
            question: string;
        };
        CrossMeetingChatResponse: {
            answer: string;
        };
    };
}
EOF
}

# --- 1. TS mirror: generated schema key vs handwritten interface -------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
cat > "$r/src/api-client.ts" <<'EOF'
export interface SearchResult {
  meetingId: string;
  score: number;
}
EOF
out=$(run "$r")
check "generated TS file detected" "$(printf 'GEN\tsrc/types/api.generated.ts\tts')" "$out"
check "handwritten mirror reported" "$(printf 'MIRROR\tsrc/types/api.generated.ts\tSearchResult\tsrc/api-client.ts:1')" "$out"
rm -rf "$r"

# --- 2. stale predates comment near the mirror -------------------------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
cat > "$r/src/api-client.ts" <<'EOF'
// Hand-written: the committed api.generated.ts predates that addition and
// isn't regenerated in this change.
export interface SearchResult {
  meetingId: string;
}
EOF
out=$(run "$r")
check "stale comment reported" "STALECOMMENT" "$out"
check "comment tied to the nearest mirror" "$(printf '\tSearchResult\t')" "$out"
check "comment excerpt carries the claim" "predates that addition" "$out"
rm -rf "$r"

# --- 3. fresh artifact, no mirrors: clean is a positive record ---------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
cat > "$r/src/api-client.ts" <<'EOF'
import type { components } from './types/api.generated';
type SR = components['schemas']['SearchResult'];
export function search(): SR[] { return []; }
EOF
out=$(run "$r")
check "clean generated file gets OKGEN" "$(printf 'OKGEN\tsrc/types/api.generated.ts')" "$out"
absent "no MIRROR without a re-declaration" "MIRROR" "$out"
check "summary counts zero mirrors" "mirrors=0" "$out"
rm -rf "$r"

# --- 4. Go mirror: *.gen.go vs handwritten struct ----------------------------
r=$(newrepo)
mkdir -p "$r/api"
cat > "$r/api/types.gen.go" <<'EOF'
// Code generated by oapi-codegen. DO NOT EDIT.
package api

type SearchResult struct {
	MeetingID string
}
EOF
cat > "$r/api/models.go" <<'EOF'
package api

type SearchResult struct {
	MeetingID string
}
EOF
out=$(run "$r")
check "generated Go file detected" "$(printf 'GEN\tapi/types.gen.go\tgo\tboth')" "$out"
check "Go mirror reported" "$(printf 'MIRROR\tapi/types.gen.go\tSearchResult\tapi/models.go:3')" "$out"
rm -rf "$r"

# --- 5. generated-vs-generated is regeneration, not a mirror -----------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/other/generated"
cat > "$r/other/generated/api.ts" <<'EOF'
export interface Citation {
  meetingId: string;
}
EOF
out=$(run "$r")
absent "two generated files sharing a name is not a mirror" "MIRROR" "$out"
rm -rf "$r"

# --- 6. header-only detection: odd name, generator banner --------------------
r=$(newrepo)
cat > "$r/client_types.ts" <<'EOF'
// DO NOT EDIT. Generated by a bespoke script.
export interface WireFormat {
  version: number;
}
EOF
out=$(run "$r")
check "banner alone marks a file generated" "$(printf 'GEN\tclient_types.ts\tts\theader')" "$out"
rm -rf "$r"

# --- 7. glob-only detection: generated/ path, no banner ----------------------
r=$(newrepo)
mkdir -p "$r/generated"
cat > "$r/generated/api.ts" <<'EOF'
export interface WireFormat {
  version: number;
}
EOF
out=$(run "$r")
check "generated/ path alone marks a file generated" "$(printf 'GEN\tgenerated/api.ts\tts\tglob')" "$out"
rm -rf "$r"

# --- 8. schemas-block extraction is what finds key-only names ----------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
printf 'export interface CrossMeetingChatRequest {\n  question: string;\n}\n' > "$r/src/chat.ts"
out=$(run "$r")
check "a key-only schema name still yields a mirror" "$(printf 'MIRROR\tsrc/types/api.generated.ts\tCrossMeetingChatRequest\tsrc/chat.ts:1')" "$out"
rm -rf "$r"

# --- 9. no generated files: the N/A shape ------------------------------------
r=$(newrepo)
printf 'export interface SearchResult { id: string }\n' > "$r/client.ts"
out=$(run "$r")
check "no generated contracts reports gen_files=0" "gen_files=0" "$out"
absent "no MIRROR without a generated side" "MIRROR" "$out"
rm -rf "$r"

# --- 10. a mention is not a declaration ---------------------------------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
cat > "$r/src/api-client.ts" <<'EOF'
// SearchResult comes from the generated types.
const label = "SearchResult";
export function name(): string { return label; }
EOF
out=$(run "$r")
absent "comments and strings never count as mirrors" "MIRROR" "$out"
rm -rf "$r"

# --- 11. test-file mirrors are emitted, not silently dropped -----------------
r=$(newrepo)
mkdir -p "$r/api"
cat > "$r/api/types.gen.go" <<'EOF'
// Code generated by oapi-codegen. DO NOT EDIT.
package api

type SearchResult struct {
	MeetingID string
}
EOF
printf 'package api\n\ntype SearchResult struct {\n\tMeetingID string\n}\n' > "$r/api/foo_test.go"
out=$(run "$r")
check "a test-file mirror is still a record" "$(printf 'MIRROR\tapi/types.gen.go\tSearchResult\tapi/foo_test.go')" "$out"
rm -rf "$r"

# --- 12. the name cap announces itself ----------------------------------------
r=$(newrepo)
{ printf '// Code generated by protoc. DO NOT EDIT.\n'
  awk 'BEGIN { for (i = 0; i < 401; i++) printf "export type GeneratedName%03d = string\n", i }'
} > "$r/big.generated.ts"
out=$(run "$r")
check "401 names trip the announced cap" "NOTE" "$out"
check "cap note names what was dropped" "name-cap" "$out"
rm -rf "$r"

# --- 13. the hand-written-here comment variant --------------------------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
cat > "$r/src/api-client.ts" <<'EOF'
// Hand-written here (rather than pulled from api.generated.ts).
export interface Citation {
  meetingId: string;
}
EOF
out=$(run "$r")
check "hand-written-here phrasing is caught" "STALECOMMENT" "$out"
rm -rf "$r"

# --- 14. non-git directory still scans -----------------------------------------
d=$(mktemp -d)
gen_ts "$d/src/types/api.generated.ts"
mkdir -p "$d/src"
printf 'export interface SearchResult { id: string }\n' > "$d/src/client.ts"
out=$(run "$d")
check "outside git the scan still runs" "$(printf 'MIRROR\tsrc/types/api.generated.ts\tSearchResult')" "$out"
rm -rf "$d"

# --- 15. exit 0 with findings ---------------------------------------------------
r=$(newrepo)
gen_ts "$r/src/types/api.generated.ts"
mkdir -p "$r/src"
printf 'export interface SearchResult { id: string }\n' > "$r/src/api-client.ts"
( cd "$r" && bash "$SCRIPT" >/dev/null 2>&1 )
code=$?
if [[ "$code" == "0" ]]; then ok "exit 0 despite findings"; else bad "exit 0 despite findings (got $code)"; fi
rm -rf "$r"

echo
echo "contract-mirror.sh: $pass passed, $fail failed"
[[ "$fail" -eq 0 ]] || exit 1
